Models/LibraryBook.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace AkaLibraryMVC.Models
{
    [Table("Library_Book")]
    public class LibraryBook
    {
        [Key]
        public int LibraryBookSId { get; set; }

        public int LibraryId { get; set; }

        public int BookId { get; set; }

        public int TotalPurchasedByLibrary { get; set; }

        public virtual BookTitle BookTitle { get; set; }

        public virtual Library Library { get; set; }

        public virtual ICollection<BookSignedOut> BooksSignedOut { get; set; }

        public virtual int AvailableCount
        {
            get
            {
                return TotalPurchasedByLibrary - BooksSignedOut.Count(bso => bso.WhenReturned == null);
            }
        }
    }
}

Controllers/LibraryBookController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using AkaLibraryMVC.Models;

namespace AkaLibraryMVC.Controllers
{
    public class LibraryBookController : Controller
    {
        private readonly LibraryModel _db = new LibraryModel();

        // GET: LibraryBook/5
        // where 5- is libraryId

        public async Task<ActionResult> List(int? id)
        {
            ViewBag.LibraryName = _db.Libraries.Find(id).Name;

            var libraryBook = _db.LibraryBook
                .Include(l => l.BookTitle)
                .Include(l => l.Library)
                .Include(l => l.BooksSignedOut)
                .Where(l => l.LibraryId == id);
            var bookList = await libraryBook.ToListAsync();

            bookList = bookList.Where(b => b.AvailableCount > 0).ToList();

            return View(bookList);
        }

        // GET: LibraryBook/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var libraryBook = await _db.LibraryBook.FindAsync(id);

            if (libraryBook == null) return HttpNotFound();

            return View(libraryBook);
        }

        public async Task<ActionResult> SignOutBook(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var libraryBook = await _db.LibraryBook.FindAsync(id);

            if (libraryBook == null) return HttpNotFound();

            var bookSignedOut = new BookSignedOut
            {
                LibraryBookSId = libraryBook.LibraryBookSId,
                LibraryBook = libraryBook
            };

            return View(bookSignedOut);
        }

        [HttpPost]
        public ActionResult PostSignOutBook(BookSignedOut bookSignedOut)
        {
            if (bookSignedOut == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            bookSignedOut.LibraryBook = _db.LibraryBook.Find(bookSignedOut.LibraryBookSId);

            var errors = ValidateBookSignedOut(bookSignedOut);

            if (!errors.Any())
            {
                bookSignedOut.WhenSignedOut = DateTime.Now;

                _db.BookSignedOuts.Add(bookSignedOut);
                _db.SaveChanges();

                return RedirectToAction("List", new {id = bookSignedOut.LibraryBook.LibraryId});
            }

            ViewBag.Errors = errors;

            return View("SignOutBook", bookSignedOut);
        }

        private IEnumerable<string> ValidateBookSignedOut(BookSignedOut bookSignedOut)
        {
            const int bookSignOutMax = 2;
            var errors = new List<string>();

            if (_db.Members.Find(bookSignedOut.MemberId) == null)
            {
                errors.Add("Member Id was invalid");
            }

            var existingBookSignOuts = _db.BookSignedOuts
                .Count(bso => bso.MemberId == bookSignedOut.MemberId && bso.WhenReturned == null);

            if (existingBookSignOuts >= bookSignOutMax)
            {
                errors.Add("Member has reached sign out max limit");
            }

            return errors;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/LibraryBook/Details.cshtml
@model AkaLibraryMVC.Models.LibraryBook

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>LibraryBook</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BookTitle.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookTitle.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Library.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Library.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalPurchasedByLibrary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPurchasedByLibrary)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "List", new { id = Model.LibraryId })
</p>

Views/LibraryBook/List.cshtml
@model  IEnumerable<AkaLibraryMVC.Models.LibraryBook>

@{
    ViewBag.Title = "List of Books for Library";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Books in @Html.ViewBag.LibraryName</h2>

<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.BookTitle.Title)</th>
        <th>Total Purchased By Library</th>
        <th>Available</th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BookTitle.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalPurchasedByLibrary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AvailableCount)
            </td>
            <td>
                @Html.ActionLink("Sign Out", "SignOutBook", new { id = item.LibraryBookSId })
                @Html.ActionLink("Details", "Details", new {id = item.LibraryBookSId})
            </td>
        </tr>
    }
</table>

Views/LibraryBook/SignOutBook.cshtml
@model AkaLibraryMVC.Models.BookSignedOut
@{
    ViewBag.Title = "Sign Out Book";
    var errors = (ViewBag.Errors != null) ? (List<string>)ViewBag.Errors : new List<string>();
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>@Html.DisplayFor(model => model.LibraryBook.BookTitle.Title)</h4>
    <hr />
    
    @{
        if (errors.Any())
        {
            <ul style="background-color: red;">
                @foreach (var error in errors)
                {
                    <li>@error</li>
                }
            </ul>
        }
    }

    @using (Html.BeginForm("PostSignOutBook", "LibraryBook", FormMethod.Post))
    {
        @Html.HiddenFor(model => model.LibraryBookSId)

        <div class="row">
            <div class="col-xs-2 text-right">
                @Html.LabelFor(model => model.MemberId)
            </div>
            <div class="col-xs-10">
                @Html.TextBoxFor(model => model.MemberId)
            </div>
        </div>

        <div class="row">
            <div class="col-xs-2">
            </div>
            <div class="col-xs-10">
                <input type="submit" value="Submit" />
            </div>
        </div>
    }

    <p>
        @Html.ActionLink("Back to List", "List", new { id = Model.LibraryBook.LibraryId })
    </p>
</div>